plugins:
  - jekyll-relative-links
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-slate
title: All about <font face="Arial Black" size="7">X</font><font size="6" face="Arial Black">-</font><font size="5" face="Arial Black">Wrt</font>
name: Blog, News and Docs about X-Wrt
description: Home <a href="https://x-wrt.com/">https://x-wrt.com</a> Blog <a href="https://blog.x-wrt.com/">https://blog.x-wrt.com</a>
url: https://blog.x-wrt.com
